SLACK_CHANNEL_NAME: "rehan.ali9325"
SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
ENVIRONMENT: "prod"
ACTION_MESSAGE: "Deploying to production via Ansible"
PLAYBOOK_PATH: "playbooks/deploy-k8s.yaml"

