# --- Kubernetes Deployment Config ---
namespace: devopstitans
deploymentName: sample-app
image: nginx:latest
replicas: 2
port: 80

# --- Pipeline / Notification Config ---
SLACK_CHANNEL_NAME: "rehan.ali9325"
ENVIRONMENT: "prod"
CODE_BASE_PATH: "env/prod"
ACTION_MESSAGE: "Deploying Kubernetes to *prod* environment"
SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
KEEP_APPROVAL_STAGE: true


